### ISSUE TITLE
New temp mail service

### ISSUE THREAD

**Issue by Majestcx** [wesbos/burner-email-providers#102]
https://popmail.io/

**Comment by Majestcx** [comment]
And this list (more are already insert): https://hastebin.com/uxeyevirem.css

**Comment by Majestcx** [comment]
MX Lookup: https://hastebin.com/lonukegofu.css
Final Active domains: https://hastebin.com/axayukejay.css

**Comment by tompec** [comment]
A domain without MX records can still receive emails. The A record will be used if no MX has been found.

**Comment by Majestcx** [comment]
@tompec Oh, okay, then I'll repeat the test
Thanks

**Comment by Majestcx** [comment]
So, Lookup : https://hastebin.com/ozujitoquk.css
and results : https://hastebin.com/nenuzikedo.sm

**Comment by Majestcx** [comment]
Other checked domains : 
Lookup : https://hastebin.com/petixujera.css
Result : https://hastebin.com/xesasayuco.sm

(I am checking out huge lists from sites that I've found, so there will be a lot of duplicates between checks)

**Comment by emh-rowland-oconnor** [comment]
Thanks.

popmail.io added.

Will go through the hastebin lists soon to sanity check / de-dupe etc.

**Comment by emh-rowland-oconnor** [comment]
173 new domains after filtering / de-dupe.

Committed to master branch.

Thank you

**Comment by tompec** [comment]
@emh-rowland-oconnor Thanks for your work, but I think you should be careful when adding bulk domains like that. Most of them are not disposable.

**Comment by emh-rowland-oconnor** [comment]
@tompec 

I did remove quite a few non-disposable ones (e.g. qq.com). Must have missed a few.

Any pointers to those that you spotted appreciated.

**Comment by tompec** [comment]
I probably missed some domains too, but I think it's better to have only verified domains, it's easier to add a new one than to remove non disposable emails.
