### ISSUE TITLE
New domains

### ISSUE THREAD

**Issue by Olden** [wesbos/burner-email-providers#111]
email.ru
exn.ru
max.ru
nextmail.ru
rol.ru
visto.com
xaker.ru
pop3.ru

**Comment by mauriciogofas** [comment]
mozej.com

**Comment by emh-rowland-oconnor** [comment]
@ mauriciogofas
mozej.com added (Mohmal alias)

@Olden 
Thank you. The .ru domains seem to be ISP's rather than DEA's. Am I missing something?

**Comment by thisandagain** [comment]
zebra.email

**Comment by emh-rowland-oconnor** [comment]
Added. Thanks,

**Comment by thisandagain** [comment]
Thanks @emh-rowland-oconnor
