### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Betree** [wesbos/burner-email-providers#114]
Could you please add a LICENSE to the repository ?

Thanks :wink:

**Comment by BlakeGardner** [comment]
Agree, only the original author can add a license. MIT is probably best. https://opensource.org/licenses/MIT

**Comment by wesbos** [comment]
submit a PR and ill merge it :)

**Comment by BlakeGardner** [comment]
PR created

**Comment by Betree** [comment]
Merged in #119. Thanks !
