### ISSUE TITLE
Deaguard API

### ISSUE THREAD

**Issue by knubew** [wesbos/burner-email-providers#116]
Hi,

sorry for posting in the issues section, but I don't know a better way.

Since 03-FEB-2018 all calls to the Deaguard API (https://www.deaguard.eu.org/) throw "526: Invalid SSL certificate" errors. I can't find an email address of the webmaster for the Deaguard API project.

Do you have any idea how to proceed in this problem?

**Comment by emh-rowland-oconnor** [comment]
Hello.

I do have the owner's contact details but won't post these details publically out of courtesy.

Can you please drop me a support ticket via my [helpdesk](https://help.emailhippo.com/en/support/solutions/articles/12000036593-information-security-management-system-policy) and I'll follow up with you privately.
