### ISSUE TITLE
New domains and services

### ISSUE THREAD

**Issue by ivan-kolmychek** [wesbos/burner-email-providers#127]
Services:
- `https://mytemp.email`
- `https://lroid.com/`
- `https://givmail.com/`

A lot of their domains are already in the list, but some are not yet.

#### `givmail.com`
(I have not found these on their site, they have A records pointing at same IP and very similar activity.)

```
robo3.site
robo3.me
robo3.club
robot2.me
robot2.club
```

#### `mytemp.email`
```
rblx.site
```

#### `lroid.com`:
```
giyam.com
```

**Comment by ivan-kolmychek** [comment]
Also, `robot-mail.com` (both service and domain).

**Comment by emh-rowland-oconnor** [comment]
Thank you.

Services and domains have been added.
