### ISSUE TITLE
163.com is not burner email

### ISSUE THREAD

**Issue by wizard-merlin** [wesbos/burner-email-providers#132]
163.com is a free email provider but it's not a burner email provider. Actually it is a very popular email provider in China. The domain name 163.com has a high ranking on Alexa https://www.alexa.com/siteinfo/163.com .

**Comment by wizard-merlin** [comment]
Similarly, 139.com is not a burner email either. 139.com is free email provided by China Mobile, a leading ISP in China.

**Comment by emh-rowland-oconnor** [comment]
Thank you.

Resolved in commit 0ed8e8da37896c237a5ea1d7030dc4f668999c06
