### ISSUE TITLE
.id.au 2LD domain listing blocking legitimate Australian personal domains

### ISSUE THREAD

**Issue by gsiemon** [wesbos/burner-email-providers#137]
I have come across this list as a commercial website is using this list.  I cannot use my email address to register an account with them (<name>@siemon.id.au) as you have listed the .id.au 2LD.  

.id.au is a 2LD for personal domains for Australian citizens.  In Australia .com.au, .net.au etc are only allowed to be sold to businesses and checks are done by the domain registrars.  The .id.au 2LD is controlled by auDA which is the regulator for the .au TLD.  No one owns the .id.au 2LD.  Please see this information: https://www.auda.org.au/industry-information/au-domains/ 
and also here: https://www.domainregistration.com.au/news/id-au-domain-names.php.  

By blocking .id.au you are affecting >13000 domains the vast majority of which are legitimate.

Can you please remove .id.au from your list and consider blocking at the domain.id.au level?

If you'd like more information please let me know.

**Comment by emh-rowland-oconnor** [comment]
Helle @gsiemon .

Thank you for pointing this out. The TLD has been removed from the list.

Entries on this list are sourced by the community. Whilst we do best efforts to QA submissions, occasionally the odd anomaly / false positive does slip through the net.
