### ISSUE TITLE
Double entries

### ISSUE THREAD

**Issue by knubew** [wesbos/burner-email-providers#175]
The list has double entries:

spaereplease.com
spaerePlease.com

Importing the list into a database can result in a primary key error.

**Comment by emh-rowland-oconnor** [comment]
Ok and thank you.

Will get this fixed.

**Comment by ali654** [comment]
Sir Please Restore this domain
siftportal.ru
i have created a maxbounty account on this domain and my account is blocked i want to check my mail i don't have any other option.
i work hard to earn money and i have more than 100$ in this account
kindly sir restore this domain for one day
Thanks
this is a huge help for me
Thanks
