### ISSUE TITLE
Might want to check this site out

### ISSUE THREAD

**Issue by 737simpilot** [wesbos/burner-email-providers#177]
I don't know too much about Github and its pull requests, but this site is loaded with temp emails you may want to add. `https://clipmails.com/`

Here's another: `https://faketempmail.com/`

And another: `https://tempr.email/en/`

Here are others. 

nwytg.net

risencraft.ru

lalamailbox.com

appdollars.com

verifymail.win

owlymail.com

battricks.com

supere.ml 

drope.ml

SpamSpamEverywhere.org

temporary-email.com

umail2.com

1secmail.com

1secmail.org

1secmail.net

20minutemail.it

This site is rotten to the core and perhaps should be reported to Google. `https://storegmail.com/`

I'll keep hunting them down latter.

**Comment by 737simpilot** [comment]
Looks like non of these have been implemented. By forum depends on this list and without it users will be able to use temp emails.

**Comment by emh-rowland-oconnor** [comment]
Hey @737simpilot .

Thank you for the list and sorry for the delay.

These will be added in the next day or so.

p.s. A faster way of getting the list updated is with a pull request (although I appreciate that not everyone knows how to do this).

**Comment by 737simpilot** [comment]
Yeah, I'm not Github orientated so I have to figure out how to do a pull request.

**Comment by emh-rowland-oconnor** [comment]
Addressed in #179
