### ISSUE TITLE
No packagist support

### ISSUE THREAD

**Issue by secit-pl** [wesbos/burner-email-providers#183]
This repo has composer.json but it's not listed on https://packagist.org/ . Could you please add it there?

**Comment by wesbos** [comment]
This is just a list, I think if people want to (and they have) create packages that consume the list, that is great. Ill remove that file

**Comment by secit-pl** [comment]
Could you please bring it back? I'm using this list in my Symfony validator https://github.com/secit-pl/validation-bundle#burneremail and added your composer.json to packagist. But when you removed the composer.json I'm no longer able to update the packagist details.

**Comment by secit-pl** [comment]
Hey @wesbos could you please bring it back? 🙏

**Comment by secit-pl** [comment]
@wesbos bump!
