### ISSUE TITLE
10minutemail.net changes

### ISSUE THREAD

**Issue by Sublime45** [wesbos/burner-email-providers#19]
I think 10minutemail.net changed their provided emails domain to @laoeq.com.
Maybe you can add that to the list as well. 

![image](https://cloud.githubusercontent.com/assets/3041560/15186963/cb6ebbe0-17a7-11e6-8e40-d2d3c16bbf01.png)

**Comment by tsamu** [comment]
also mvrht.com

**Comment by emh-rowland-oconnor** [comment]
Added in #32
