### ISSUE TITLE
Ded is Dead

### ISSUE THREAD

**Issue by etanb** [wesbos/burner-email-providers#197]
Hi,

The listed Go packaged, `ded`, doesn't work at all. All queries return false.

**Comment by emh-rowland-oconnor** [comment]
Hi.

Thank you.

Please contact the [project owner](https://github.com/namreg/ded) for help with this.

**Comment by etanb** [comment]
@emh-rowland-oconnor I flagged this because it's prominently flagged in your README yet is completely broken.

**Comment by emh-rowland-oconnor** [comment]
Ok.

Have updated the link to show "reported not working".

Thank you for reporting.
