### ISSUE TITLE
Please consider unblocking "21cn.com".

### ISSUE THREAD

**Issue by ShikiSuen** [wesbos/burner-email-providers#204]
21cn is an enterprise email service provider in Mainland China.
I knew this 20 years ago, and I just found that they are still providing services to both enterprise customers and individual customers. This provider appears to be acquired by China Telecom.

**Comment by ShikiSuen** [comment]
Also, QQ.com isn't a total spam mail provider.
QQ is a famous instant messenger, and every QQ account (named as UID number) comes with a free email account as "UID"@qq.com 。

**Comment by wesbos** [comment]
QQ isn't on this list

**Comment by ShikiSuen** [comment]
Okay. I do apologize for my fuzzy mind. It was my mistake after merging multiple blacklists from multiple GitHub repos, and I messed up their sources.
