### ISSUE TITLE
composer.json

### ISSUE THREAD

**Issue by secit-pl** [wesbos/burner-email-providers#213]
Hi,

My issue https://github.com/wesbos/burner-email-providers/issues/183 was closed and I cannot get the response there so I'm creating a new one.

Could the removed file package.json be readded? I'm using this list in my Symfony validator https://github.com/secit-pl/validation-bundle#burneremail and added your composer.json to packagist. But when you removed the composer.json I'm no longer able to update the packagist details.
This caused that all projects which are using my package cannot be updated and new packages cannot be installed. This can be fixed only by removing my package from the dependencies.

Adding a composer.json won't make any problem for you (the content of the previously present file is perfectly fine) and will help me and others in using the list in PHP projects.

**Comment by secit-pl** [comment]
I have created a PR https://github.com/wesbos/burner-email-providers/pull/214 which solves the described problem.

**Comment by wesbos** [comment]
Sorry! All good now
