### ISSUE TITLE
Please add this new temporary email service

### ISSUE THREAD

**Issue by xianx** [wesbos/burner-email-providers#217]
I use you list for long time. Thank for your service.

Recently there any some app out there that has no web interface and has android app. So its difficult to get email address of them.

I am getting some spam email from a service hourly-mail dot com as its an app it generate many temporary email address. I got below domain as temporary email those are using to spam on my site. 

baos.site
wowbd.fun
hourlymail.pw
promotemd.com
ntalecom.net
fctemp.top
sflexi.net

Please add them to your list.

Also there are many app that can generate these type of temporary email. You can research and add them too.

Thanks a lot for you initiative.

**Comment by emh-rowland-oconnor** [comment]
Added in PR #218 

Thank you.
