### ISSUE TITLE
Strange-looking domain names

### ISSUE THREAD

**Issue by gnikolaidis** [wesbos/burner-email-providers#219]
Hi, thanks for your work, it is really nice to have all these pesky domains in one list. Within the list, I stumbed upon:

müll.email (non-7bit-ASCII)
müllemail.com (non-7bit-ASCII)
müllmail.com (non-7bit-ASCII)
ywoe@mailed.ro (not a domain name)

Do you think these can be removed?

**Comment by emh-rowland-oconnor** [comment]
Hello.

Resolved in #221
