### ISSUE TITLE
Integrate extra lists

### ISSUE THREAD

**Issue by yetithefoot** [wesbos/burner-email-providers#232]
There are other lists we may integrate, should we?
https://github.com/ivolo/disposable-email-domains/blob/master/index.json
https://github.com/FGRibreau/mailchecker/blob/master/list.txt

**Comment by emh-rowland-oconnor** [comment]
It's an idea worth thinking about.

There are some practical things to work out on workflow / QA etc such as:

* How to keep the merges up to date. (Synchronization)
* Dupes?

Perhaps another way of doing it would be to create a service that ingests lists and does this workflow automatically?

At this point I have more questions than answers...

**Comment by yetithefoot** [comment]
I suggest to not overthink the process and rely on forks and pull requests at the moment. There are many things to do, but main idea is to keep actual list of burner emails.

As for dupes it's not so big problem, just unique the list and commit.

I can send such PRs from time to time and handle the dupes issue.

**Comment by emh-rowland-oconnor** [comment]
@yetithefoot Great. Thank you.

Let's go for this and see how it works out.
