### ISSUE TITLE
Spamgourmet not really burner

### ISSUE THREAD

**Issue by mikedlr** [wesbos/burner-email-providers#24]
Hi;  not completely sure what the intent of your list is, however

a) spamgourment.com doesn't bounce
b) by default it does deliver multiple mails
c) where normal, requested mails are being delivered then the users will normally keep getting them
d) spamgourmet does accept abuse reports and block abusive users 
e) spamgourmet addresses are tracable by their admins to a specific logged in user

As such I don't think that it would either "drive up bounces" or "hurt deliverability" any more than the other service providers such as google where people can easily get multiple mail addresses.  For any use other than gathering mails for spamming it seems to me that spamgourmet.com shouldn't be on your list of burner email addresses.  I'd propose deleting their domains from your list.

**Comment by wesbos** [comment]
Hey -thanks for the issue.

This is a repo of disposable email addresses and I think that is exactly what spamgourmet is, no?

**Comment by mikedlr** [comment]
hi;

No, spamgourment isn't disposable email addresses in the sense like mailinator and co.  There is one account per person which can have more than one address and the person owns the email addresses which stay around attached to that account.  They _can_ be limited in the number of emails they accept but normally, if a person subscribes to the email address to a mailing list they will just allow indefinite mails.  Also they can be recharged.

The email address would only be disposable if it was used by a spammer when I you would shut it down.  Similar to the way google keyword+mainaccount@gmail.com addresses work.  

So I guess a spammer might think of them as disposable addresses, but a normal mailer wouldn't.  I have a number of spamgourmet addresses that I've been using for years and years (e.g. for redhat bugzilla)

**Comment by wesbos** [comment]
I see - makes sense. you can submit a PR to take it out
