### ISSUE TITLE
Problem with special chars while database import

### ISSUE THREAD

**Issue by knubew** [wesbos/burner-email-providers#248]
I think the entry "yêuniverse.net" should be removed because it uses the special char ê.

**Comment by legraphista** [comment]
Instead of removing the entry, maybe should have used its normalized version `XN--YUNIVERSE-L4A.NET`? 
https://whois.domaintools.com/xn--yuniverse-l4a.net

**Comment by emh-rowland-oconnor** [comment]
It is already included as "yeuniverse.net"

**Comment by legraphista** [comment]
Ah, so it was a misspelling of the domain
