### ISSUE TITLE
netguide.com entry in emails.txt

### ISSUE THREAD

**Issue by SylvainLeprovost** [wesbos/burner-email-providers#259]
Hi,

I have noticed that my website, Netguide.com, is listed as a disposable emails provider in emails.txt. 

We never has been providing this kind of service, at least since I took ownership of this domain-name, in 2008 I think 😉 

We do have a page on Netguide listing providers of temporary emails there : 
https://www.netguide.com/Emails-jetables-ou-temporaires/ But, it is only a listing of providers not an offer we are making ourselves.

Maybe, because this page is in French, one has mistakenly thought that we were providing this service.

I would appreciate Netguide.com to be removed of this list. I am currently blocked in a registration process because of this, and I would like to keep my regular email adress.

Thank you 🙏

**Comment by emh-rowland-oconnor** [comment]
Removed in PR #260 .
