### ISSUE TITLE
File is getting too huge

### ISSUE THREAD

**Issue by wesbos** [wesbos/burner-email-providers#265]
Any thoughts on how to deal with this? It makes adding a domain via github too hard. 

Ideas:

* Cull the list of expired domains. I'm sure there are some in there
* have a second file?

**Comment by wesbos** [comment]
looks like there is a PR to do this : https://github.com/wesbos/burner-email-providers/pull/249

**Comment by mathe42** [comment]
I have a solution have a script to check all MX Records. If error domain is added to a list. Add this script in a PR. This will not ilminate all old domains but many (4518 wich start with a number).


Run the script take some time so I will create a PR in the next days.

**Comment by lindell** [comment]
#249 Does only look for invalid top-level domains.
The real list of invalid domains is much bigger if we count all domains where it's impossible sending emails to.

I made a script a month ago, that was going through all domains and checking the MX-record for all domains.
This resulted in around an 80% reduction. From `110434` to `18126` domains.

The only problem is that this is not completely static, and when running the script again, the day after, around 5 new domains did now have a valid MX-record.

Would we be fine with some false positive removals? In that case, I could continue to run the script, and any domain that had a valid MX-record any run, would be added to the resulting list.

**Comment by wesbos** [comment]
Ahh interesting.. 

Are the MX records valid because the domains are re-activated?

**Comment by lindell** [comment]
That is my guess. Or that the domain itself was active all the time. But no MX-record was set.

**Comment by wesbos** [comment]
What if we keep a list of those inactivated domains and then periodically check and add them back in? Could be done via a github action. 

If the domain is no longer registered, just remove it entirely.

If the domain is registered  but has no MX records, put it in storage.

If the domain has MX records, keep it in the list.

**Comment by lindell** [comment]
Don't know if we gain anything from separating no MX record domains and inactivated domains. But I really like the idea of having an evergreen list of domains that is currently active that may re-add things that seemed to be inactive 🙂 

The "storage" could even just be the git-history, the script could just look for "cleaning"-commits and check for domains removed there 🤔

**Comment by lindell** [comment]
@wesbos What language would you prefer this be written in? JS?

**Comment by Pierstoval** [comment]
I have some other ideas regarding this.

What about providing this service as an open-source self-hostable SaaS platform?

I mean, even `curl`-ing Github could be enough, but I think it's easier for everyone to be able to have an external system, and having it self-hostable allows people to be able to manage their own instance and just update it every once in a while.

This way, the repository itself wouldn't have to handle the way the data are provided to end-users: either one centralized website (I can sponsor it if necessary, but I guess other people could also sponsor it if necessary), or anyone could use their own infrastructure to provide a federated network that use the exact same data source.

WDYT?

**Comment by wesbos** [comment]
Ideally yes, JS or TS

**Comment by wesbos** [comment]
fixed https://github.com/wesbos/burner-email-providers/pull/388
