### ISSUE TITLE
Syntaxerror in emails.txt

### ISSUE THREAD

**Issue by smeinecke** [wesbos/burner-email-providers#269]
In https://github.com/wesbos/burner-email-providers/blob/master/emails.txt there seems to be an "import" error as the following line is not a valid domain name :)

pradajapan.orgpradajapan.orgpradajapan.orgpradajapan.orgpradajapan.orgpradajapan.orgpradajapan.orgpradajapan.orgpradajapan.org

**Comment by emh-rowland-oconnor** [comment]
resolved in pr #272 

Thank you.
