### ISSUE TITLE
Re-distributed in my R package

### ISSUE THREAD

**Issue by jcpsantiago** [wesbos/burner-email-providers#278]
👋 hello everyone! Great job compiling and maintaining this. I wanted to let you know I am re-distributing this list as part of an R package I wrote https://github.com/jcpsantiago/isfreemail. Hope that's ok, I'm linking back to this repo.

I'm also interested in a good list of free (as in _the domain provides emails free of charge for some period of time_, of which burners could be seen as a subset (that's how I'm packaging this). I only found gists, but no repo like yours where people also take care to prune the list etc.

**Comment by wesbos** [comment]
awesome! totally fine
