### ISSUE TITLE
Looking for a few hands

### ISSUE THREAD

**Issue by wesbos** [wesbos/burner-email-providers#31]
I know there are a few of you who use this repo a lot - looking to give commit access to a few people who don't mind vetting pull requests

**Comment by emh-rowland-oconnor** [comment]
Yep, I'm in.

**Comment by wesbos** [comment]
Added!

**Comment by emh-rowland-oconnor** [comment]
Thanks @wesbos.

I'm vetting / merging / updating / sanitizing / consolidating..
