### ISSUE TITLE
No permissions to push a branch and create a PR

### ISSUE THREAD

**Issue by Alex-Bogdanov** [wesbos/burner-email-providers#313]
Hi! I have a bunch of new dark emails that I've discovered recently which are not in @wesbos list. Want to share, but looks like no permission for public contribution to your project:
```
ERROR: Permission to wesbos/burner-email-providers.git denied to Alex-Bogdanov.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```
Anybody can explain the policy of contribution here?

**Comment by mathe42** [comment]
You have to fork this repository and push to that fork and not directly to this. Than create a PR from your fork to this repository.

**Comment by emh-rowland-oconnor** [comment]
Hi.

Please make changes (in your own forked repo) and then submit a pull request.
