### ISSUE TITLE
hush.com listed, but is part of hushmail.com (premium email provider)

### ISSUE THREAD

**Issue by rdlugosz** [wesbos/burner-email-providers#350]
Not sure what the policy is on this, but a user contacted me today when they couldn't get a free trial due to their "disposable email address". They had a `@hush.com` address, which looks to be a part of the hushmail.com service. That's a premium provider, so even if they do offer temporary addresses, does it really belong on the list of burner domains?

**Comment by wesbos** [comment]
sounds fair - removed it
