### ISSUE TITLE
Please remove ProtonMail domains

### ISSUE THREAD

**Issue by ghost** [wesbos/burner-email-providers#422]
Hi!

Please remove ProtonMail domains from your list. Yes, they provide anonymous registration, but outlook (from Microsoft evil corp) provides anonymous registration too!

Here is a proof:

https://github.com/disposable/disposable/assets/152306456/0834a69a-5944-4262-9349-3853e1852eff

You can simply create disposable mail account on outlook. So… Why blocking Proton but not Outlook?

Here is the list of domains that should be removed:

```
protonmail.ch
proton.me
pm.me
simplelogin.com
silomails.com
slmails.com
simplelogin.fr
aleeas.com
slmail.me
8shield.net
dralias.com
passinbox.com
passfwd.com
passmail.com
passmail.net
```

**Comment by Nbnchfugug** [comment]
https://github.com/wesbos/burner-email-providers/issues/422#issue-2014732132

`protonmail.com` forgotten

### THIS SHOULD BE UNBLOCKED

```
protonmail.ch
protonmail.com
proton.me
pm.me
simplelogin.com
silomails.com
slmails.com
simplelogin.fr
aleeas.com
slmail.me
8shield.net
dralias.com
passinbox.com
passfwd.com
passmail.com
passmail.net
```

**Comment by Nbnchfugug** [comment]
@emh-rowland-oconnor, @mtmail, @peq42, @alexharrington, @smeinecke, @beeyev and other contributors. Please remove this domains.

**Comment by mtmail** [comment]
This repository doesn't hae a ignore list. I'm not the maintainer.

**Comment by emh-rowland-oconnor** [comment]
what's changed since #414?

- Signups still possible using other DEAs as backup emails
- Zero friction / user identity verification

**Comment by Brendan-D15** [comment]
Yahoo also provides temporary/burner emails:
https://help.yahoo.com/kb/SLN28815.html

**Comment by Tepik47** [comment]
@emh-rowland-oconnor 
### READ THIS CAREFULLY (and follow links)

What will you say about such websites:
1. [One (link)](https://smailpro.com/advanced)
2. [Two (link)](https://tempmail.dev/en/Gmail)
3. [Three (link)](https://www.emailnator.com)

All three websites provides **DISPOSABLE** gmail addresses.

So you MUST block gmail.

Also. Apple provides **DISPOSABLE** solutions too.

[Proof one](https://www.idownloadblog.com/2021/09/21/apple-hide-my-email-icloud-website/) and [proof two](https://support.apple.com/guide/icloud/stop-using-or-reactivate-addresses-mm3adb030cbf/icloud) (official manual)

So you MUST block ICloud.

Also. Outlook provides **DISPOSABLE** addresses. [Proof](https://support.microsoft.com/en-us/office/add-or-remove-an-email-alias-in-outlook-com-459b1989-356d-40fa-a689-8f285b13f1f2). You can create and delete three ones per day.

So you MUST block Outlook.

Do you think it is end? Hell no!

Yahoo provides **DISPOSABLE** mails. [Proof](https://help.yahoo.com/kb/SLN28815.html)

So you MUST block Yahoo.

### IT IS CRITICAL FOR UNDERSTANDING TO FOLLOW ALL OFFICIAL LINKS IN THIS POST TO GET PROOFS.

So block:
```
gmail.com
outlook.com
icloud.com
yahoo.com
```

Or unblock Proton.

**Comment by Tepik47** [comment]
@stetsed, he blocked not only Proton. Also Tutanota (see https://github.com/wesbos/burner-email-providers/issues/420), Skiff (see https://github.com/wesbos/burner-email-providers/issues/423)

**Comment by aiko-incr** [comment]
why remove proton domein why do you wanna tracka nd hack poeple that badly
