### ISSUE TITLE
Add missing 10 minute mail domains

### ISSUE THREAD

**Issue by nullbadger** [wesbos/burner-email-providers#426]
Hello,

The domains associated with the 10 minute mail service appears to be incomplete. Below I am including a list of domains also associated with this service for their addition to the existing list.

https://www.emailnator.com/

<img width="540" alt="Screenshot 2023-12-05 at 07 33 46" src="https://github.com/wesbos/burner-email-providers/assets/152968110/e4dde25e-9f26-4dca-8ea9-bef0571bd25a">

tmpmailtor.com
googlemail.com
gmail.com
smartnator.com

**Comment by emh-rowland-oconnor** [comment]
Hi.
Thank you.
Can you please add PR for the following domains:
tmpmailtor.com
smartnator.com

**Comment by emh-rowland-oconnor** [comment]
> I would need to do all the domains listed to ensure I am capturing all burner mails provided by this service.

Can't add googlemail.com and gmail.com. Sorry.
