### ISSUE TITLE
Remove Protonmail domain

### ISSUE THREAD

**Issue by Timmi5853** [wesbos/burner-email-providers#431]
Hi!

You already removed Tutanota domains (https://github.com/wesbos/burner-email-providers/commit/3ab2c47c0529ed20dbf96883cca661e76a3ebb75) same service as Proton.

Not Proton, nor Tuta is **NOT** disposable mail provider.

Even Yahoo ([proof](https://help.yahoo.com/kb/SLN28815.html)) and ICloud ([proof](https://support.apple.com/guide/icloud/what-you-can-do-with-icloud-and-hide-my-email-mme38e1602db/icloud)) provides disposable mail feature.

I ask you to remove Proton domains from disposable list (I will create PR)

**Comment by Timmi5853** [comment]
@wesbos @emh-rowland-oconnor  https://github.com/wesbos/burner-email-providers/pull/432 please take a look

**Comment by yrahul3910** [comment]
Thanks for removing these!
