### ISSUE TITLE
Add disposable domain - lendfash.com

### ISSUE THREAD

**Issue by attenzione** [wesbos/burner-email-providers#450]
![image](https://github.com/wesbos/burner-email-providers/assets/284987/c07839c9-21b8-43aa-aab5-e826eaa226e0)

**Comment by wesbos** [comment]
send a PR please!

**Comment by mtmail** [comment]
@wesbos I see both domains are in emails.txt so this can be closed.

```
$ grep lendfash.com emails.txt
lendfash.com
mail.lendfash.com

$ grep ebuthor.com emails.txt
ebuthor.com
mail.ebuthor.com
```
