### ISSUE TITLE
Invalid burner domain

### ISSUE THREAD

**Issue by nullpainter** [wesbos/burner-email-providers#459]
My personal domain `deity.co.nz` has somehow managed to be added to this list. I've owned this domain for over a decade, and use it only for personal email. Can this be removed with urgency, as it is preventing https://forwardemail.net/ from delivering my email (as of yesterday).

**Comment by wesbos** [comment]
removed! https://github.com/wesbos/burner-email-providers/commit/c51ee26235a6cf16eb17a5eca2e08e04577dbdd5 

looks like that whole PR was full of nonsense domains

**Comment by nullpainter** [comment]
Phew, thank you! Not your fault, but it's a bit scary the flow-on effect something like this has - Forward Email uses https://raw.githubusercontent.com/disposable/disposable-email-domains/master/domains.json which in turn aggregates from a number of sources, one of which is yours.

Not sure what the solution is. Checking each one is clearly impractical for a large list. Perhaps asking for light evidence / process in PRs about where domains came from?

**Comment by Igloczek** [comment]
I've created a PR that removes all domains related to forwardemail.net - #461
