### ISSUE TITLE
Undo PR that added hundreds of false positives

### ISSUE THREAD

**Issue by titanism** [wesbos/burner-email-providers#460]
The email service https://forwardemail.net was even added, that entire PR should be reverted

https://github.com/wesbos/burner-email-providers/pull/457/commits/22f292859e3c3bcb4a4a32fe8e38f0e2388a410d#diff-4508c317bed040cf9bb04113dda6cb611c4043cdf95ce8f60042f2b988f363daR7852

<img width="373" alt="Screen Shot 2024-05-08 at 9 25 32 PM" src="https://github.com/wesbos/burner-email-providers/assets/101466223/eab4e86e-6eab-418e-be34-ac928c5647a9">

**Comment by wesbos** [comment]
Fixed here: https://github.com/wesbos/burner-email-providers/pull/461
