### ISSUE TITLE
Go GRPC/JSON API

### ISSUE THREAD

**Issue by 0x19** [wesbos/burner-email-providers#67]
Hey!

As I badly needed your list I wanted to, in the return, create something that can be used by the community looking to utilize your list. 

Output is: https://github.com/0x19/disposable

Disposable is a Golang based GRPC / JSON API with support for Basic Authentication. 

Your project is git submodule. It's enough to do `make submodules` and it will update local version of this package.

It's designed to be used as standalone or as part of micro service world.

Currently following gRPC proto files are generated: Go, Python

Service is scalable, robust and well tested (unit tests for pretty much everything).

What is still missing is overall documentation and start guides that I am going to do by end of this week.

Best!

**Comment by emh-rowland-oconnor** [comment]
Updated README.md to include API services.
