### ISSUE TITLE
sneakemail is not a burner email provider

### ISSUE THREAD

**Issue by ryancdotorg** [wesbos/burner-email-providers#89]
snkmail.com and sneakemail.com are on this list and should not be. Sneakemail is a paid service. Each address is for a specific user, and the addresses do not expire.

**Comment by emh-rowland-oconnor** [comment]
Hi.

Thank you for taking the time to comment.

Always open to corrections / amendments to the list.

This repo is a list of disposable / burner email providers.

On the sneakemail landing page, it's own proposition strap line is "The Original Disposable Email Address Company".

Therefore, by its own strapline, sneakmail qualifies for inclusion.

**Comment by ryancdotorg** [comment]
Unlike other entries on this list:

* sneakemail is a paid service

* sneakemail addresses are intended for long-term use - they do not expire unless the user explicitly deletes them

Your stated goal is to avoid issues with having bounces that cause deliverability issues - that shouldn't happen with legit content people want to get, and clicking an unsubscribe link is easier than going into sneakemail and deleting the address.

**Comment by emh-rowland-oconnor** [comment]
Thank you for your points.

Understood and noted.

However, this provider still advertises itself as "The Original Disposable Email Address Company".

I am confused as to the justification why the "The Original Disposable Email Address Company" should be omitted from a list of Disposable Email Address Providers.

![19-07-2017 11-58-49](https://user-images.githubusercontent.com/14027121/28363918-468d5188-6c7a-11e7-9226-de8fa16299e7.png)

**Comment by endolith** [comment]
It's "disposable" in the sense that you can give each site a different address and delete one after the site gets hacked or sells your info.  It's not a "burner" email address.
