### ISSUE TITLE
DEAGuard - API (JSON, XML, PLAINTEXT, ETC..)

### ISSUE THREAD

**Issue by Majestcx** [wesbos/burner-email-providers#90]
After finished create my api based on this repository, I had seen that **letz** had done the same a year ago.
Well, I have create api, if anyone need it, this is the link: [https://deamails.altervista.org/](https://deamails.altervista.org/)

Thank you all

**Comment by 1337** [comment]
Is there a[ ](http://i.imgur.com/N5084p6.jpg)problem with the API?

**Comment by Majestcx** [comment]
If you're talking about **letz** APIs, I repeat no for the reason I explained above.
If you talk about these APIs, I do not think so, they work for me.

**Comment by Majestcx** [comment]
I've update APIs: [SITE](https://deamails.altervista.org/)

**Comment by emh-rowland-oconnor** [comment]
Updated README.md to include API services.
