### ISSUE TITLE
#4008 DEA providers (?)

### ISSUE THREAD

**Issue by Majestcx** [wesbos/burner-email-providers#92]
Hi, today I found this [**List**](https://pastebin.com/raw/iSEvhrbW) that includes 4008 emails including those that are on this repository, are they useful?

**Comment by emh-rowland-oconnor** [comment]
Thank you.

On 1st glance, there are some good ones in here.

We're going through in detail and will add confirmed active ones to list.

**Comment by Majestcx** [comment]
@emh-rowland-oconnor 
I don't know if it is helpful, but I've done a web request to all sites, and this is the result:
[https://pastebin.com/raw/tiwR3KpP](https://pastebin.com/raw/tiwR3KpP)

**Comment by emh-rowland-oconnor** [comment]
Thanks. Am doing something similar and with MX records. Viable domains to
be added on next few days.

**Comment by emh-rowland-oconnor** [comment]
The [team](https://github.com/emailhippo) ran these through sanity checking and filtering.

After eliminating obvious false positives (e.g. Amazon.com and Hotmail.com were in the list), we were left with a haul of 315 verified new DEA domains. 

Great find.

Thank you

**Comment by Majestcx** [comment]
@emh-rowland-oconnor 

"Hotmail.com" is still in the list.

**Comment by emh-rowland-oconnor** [comment]
Thanks.

Must have slipped through the filter.

Removed now.
